# Generated by Django 4.2.7 on 2024-03-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_sqldetails_img2_sqldetails_img3'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestions',
            name='img2',
            field=models.ImageField(blank=True, upload_to='productImages'),
        ),
    ]
