# Generated by Django 4.2.7 on 2024-03-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_interviewquestions_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestions',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
