# Generated by Django 5.0.3 on 2024-03-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_testing"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scrum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=355)),
                ("text", models.TextField(blank=True)),
                ("question", models.TextField(blank=True, max_length=255)),
                ("answer", models.TextField(blank=True)),
                ("img", models.ImageField(blank=True, upload_to="productImages")),
                ("img2", models.ImageField(blank=True, upload_to="productImages")),
                ("img3", models.ImageField(blank=True, upload_to="productImages")),
                ("url", models.URLField(blank=True, null=True)),
                ("pdf", models.FileField(blank=True, upload_to="pdfs")),
            ],
        ),
    ]
