# Generated by Django 5.0.3 on 2024-03-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_scrum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrum",
            name="img",
            field=models.ImageField(blank=True, upload_to="productImages/scrum"),
        ),
        migrations.AlterField(
            model_name="scrum",
            name="img2",
            field=models.ImageField(blank=True, upload_to="productImages/scrum"),
        ),
        migrations.AlterField(
            model_name="scrum",
            name="img3",
            field=models.ImageField(blank=True, upload_to="productImages/scrum"),
        ),
        migrations.AlterField(
            model_name="scrum",
            name="pdf",
            field=models.FileField(blank=True, upload_to="pdfs/scrum"),
        ),
    ]
