# Generated by Django 5.0.3 on 2024-04-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_alter_scrum_img_alter_scrum_img2_alter_scrum_img3_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Git",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=355)),
                ("text", models.TextField(blank=True)),
                ("question", models.TextField(blank=True, max_length=255)),
                ("answer", models.TextField(blank=True)),
                ("img", models.ImageField(blank=True, upload_to="productImages/scrum")),
                (
                    "img2",
                    models.ImageField(blank=True, upload_to="productImages/scrum"),
                ),
                (
                    "img3",
                    models.ImageField(blank=True, upload_to="productImages/scrum"),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("pdf", models.FileField(blank=True, upload_to="pdfs/scrum")),
            ],
        ),
    ]
