# Generated by Django 5.0.3 on 2024-04-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_git"),
    ]

    operations = [
        migrations.AlterField(
            model_name="git",
            name="pdf",
            field=models.FileField(blank=True, upload_to="pdfs/git"),
        ),
    ]
