# Generated by Django 5.0.3 on 2024-04-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_alter_git_pdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="DjangoRestFramework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=355)),
                ("text", models.TextField(blank=True)),
                ("question", models.TextField(blank=True, max_length=255)),
                ("answer", models.TextField(blank=True)),
                ("img", models.ImageField(blank=True, upload_to="productImages/DRF")),
                ("img2", models.ImageField(blank=True, upload_to="productImages/DRF")),
                ("img3", models.ImageField(blank=True, upload_to="productImages/DRF")),
                ("url", models.URLField(blank=True, null=True)),
                ("pdf", models.FileField(blank=True, upload_to="pdfs/DRF")),
            ],
        ),
        migrations.AlterField(
            model_name="git",
            name="img",
            field=models.ImageField(blank=True, upload_to="productImages/git"),
        ),
        migrations.AlterField(
            model_name="git",
            name="img2",
            field=models.ImageField(blank=True, upload_to="productImages/git"),
        ),
        migrations.AlterField(
            model_name="git",
            name="img3",
            field=models.ImageField(blank=True, upload_to="productImages/git"),
        ),
    ]
