# Generated by Django 5.0.3 on 2024-04-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_djangorestframework_code_block"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interviewquestions",
            old_name="answer",
            new_name="answer1",
        ),
        migrations.AddField(
            model_name="interviewquestions",
            name="answer2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interviewquestions",
            name="code_block",
            field=models.TextField(blank=True, null=True),
        ),
    ]
