# Generated by Django 5.0.3 on 2024-05-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_rename_answer_interviewquestions_answer1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DjangoRestFrameworkDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=355)),
                ("text", models.TextField(blank=True)),
                ("code_block", models.TextField(blank=True, null=True)),
                ("img", models.ImageField(blank=True, upload_to="productImages/DRF")),
                ("img2", models.ImageField(blank=True, upload_to="productImages/DRF")),
                ("img3", models.ImageField(blank=True, upload_to="productImages/DRF")),
                ("url", models.URLField(blank=True, null=True)),
                ("pdf", models.FileField(blank=True, upload_to="pdfs/DRF")),
            ],
        ),
    ]
